export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';

export const SORT_PRODUCT_REQUEST = "SORT_PRODUCT_REQUEST";
export const SORT_PRODUCT_SUCCESS = "SORT_PRODUCT_SUCCESS";
export const SORT_PRODUCT_ERROR = "SORT_PRODUCT_ERROR";
